
##############################################################
##############################################################
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# run with "wraith capture configs/BG/bids/All-BIDs-part10.yaml"
#
##############################################################
##############################################################

# (required) The domains to take screenshots of.
domains:
  prod: "https://www.benefits.gov"
  staging: "https://staging.benefits.gov"

# (required) The paths to capture. All paths should exist for both of the domains specified above.

paths:


  BID-5925:
    path: /benefits/benefit-details/5925
    selector: '[id="main"]'
  BID-5925-ES:
    path: /es/benefits/benefit-details/5925
    selector: '[id="main"]'

  BID-5926:
    path: /benefits/benefit-details/5926
    selector: '[id="main"]'
  BID-5926-ES:
    path: /es/benefits/benefit-details/5926
    selector: '[id="main"]'

  BID-5927:
    path: /benefits/benefit-details/5927
    selector: '[id="main"]'
  BID-5927-ES:
    path: /es/benefits/benefit-details/5927
    selector: '[id="main"]'

  BID-5928:
    path: /benefits/benefit-details/5928
    selector: '[id="main"]'
  BID-5928-ES:
    path: /es/benefits/benefit-details/5928
    selector: '[id="main"]'

  BID-5930:
    path: /benefits/benefit-details/5930
    selector: '[id="main"]'
  BID-5930-ES:
    path: /es/benefits/benefit-details/5930
    selector: '[id="main"]'

  BID-5931:
    path: /benefits/benefit-details/5931
    selector: '[id="main"]'
  BID-5931-ES:
    path: /es/benefits/benefit-details/5931
    selector: '[id="main"]'

  BID-5932:
    path: /benefits/benefit-details/5932
    selector: '[id="main"]'
  BID-5932-ES:
    path: /es/benefits/benefit-details/5932
    selector: '[id="main"]'

  BID-5933:
    path: /benefits/benefit-details/5933
    selector: '[id="main"]'
  BID-5933-ES:
    path: /es/benefits/benefit-details/5933
    selector: '[id="main"]'

  BID-5934:
    path: /benefits/benefit-details/5934
    selector: '[id="main"]'
  BID-5934-ES:
    path: /es/benefits/benefit-details/5934
    selector: '[id="main"]'

  BID-5935:
    path: /benefits/benefit-details/5935
    selector: '[id="main"]'
  BID-5935-ES:
    path: /es/benefits/benefit-details/5935
    selector: '[id="main"]'

  BID-5937:
    path: /benefits/benefit-details/5937
    selector: '[id="main"]'
  BID-5937-ES:
    path: /es/benefits/benefit-details/5937
    selector: '[id="main"]'

  BID-5938:
    path: /benefits/benefit-details/5938
    selector: '[id="main"]'
  BID-5938-ES:
    path: /es/benefits/benefit-details/5938
    selector: '[id="main"]'

  BID-5939:
    path: /benefits/benefit-details/5939
    selector: '[id="main"]'
  BID-5939-ES:
    path: /es/benefits/benefit-details/5939
    selector: '[id="main"]'

  BID-5940:
    path: /benefits/benefit-details/5940
    selector: '[id="main"]'
  BID-5940-ES:
    path: /es/benefits/benefit-details/5940
    selector: '[id="main"]'

  BID-5941:
    path: /benefits/benefit-details/5941
    selector: '[id="main"]'
  BID-5941-ES:
    path: /es/benefits/benefit-details/5941
    selector: '[id="main"]'

  BID-5942:
    path: /benefits/benefit-details/5942
    selector: '[id="main"]'
  BID-5942-ES:
    path: /es/benefits/benefit-details/5942
    selector: '[id="main"]'

  BID-5944:
    path: /benefits/benefit-details/5944
    selector: '[id="main"]'
  BID-5944-ES:
    path: /es/benefits/benefit-details/5944
    selector: '[id="main"]'

  BID-5945:
    path: /benefits/benefit-details/5945
    selector: '[id="main"]'
  BID-5945-ES:
    path: /es/benefits/benefit-details/5945
    selector: '[id="main"]'

  BID-5946:
    path: /benefits/benefit-details/5946
    selector: '[id="main"]'
  BID-5946-ES:
    path: /es/benefits/benefit-details/5946
    selector: '[id="main"]'

  BID-5947:
    path: /benefits/benefit-details/5947
    selector: '[id="main"]'
  BID-5947-ES:
    path: /es/benefits/benefit-details/5947
    selector: '[id="main"]'

  BID-5948:
    path: /benefits/benefit-details/5948
    selector: '[id="main"]'
  BID-5948-ES:
    path: /es/benefits/benefit-details/5948
    selector: '[id="main"]'

  BID-5949:
    path: /benefits/benefit-details/5949
    selector: '[id="main"]'
  BID-5949-ES:
    path: /es/benefits/benefit-details/5949
    selector: '[id="main"]'

  BID-5950:
    path: /benefits/benefit-details/5950
    selector: '[id="main"]'
  BID-5950-ES:
    path: /es/benefits/benefit-details/5950
    selector: '[id="main"]'

  BID-5951:
    path: /benefits/benefit-details/5951
    selector: '[id="main"]'
  BID-5951-ES:
    path: /es/benefits/benefit-details/5951
    selector: '[id="main"]'

  BID-5952:
    path: /benefits/benefit-details/5952
    selector: '[id="main"]'
  BID-5952-ES:
    path: /es/benefits/benefit-details/5952
    selector: '[id="main"]'

  BID-5953:
    path: /benefits/benefit-details/5953
    selector: '[id="main"]'
  BID-5953-ES:
    path: /es/benefits/benefit-details/5953
    selector: '[id="main"]'

  BID-5954:
    path: /benefits/benefit-details/5954
    selector: '[id="main"]'
  BID-5954-ES:
    path: /es/benefits/benefit-details/5954
    selector: '[id="main"]'

  BID-5958:
    path: /benefits/benefit-details/5958
    selector: '[id="main"]'
  BID-5958-ES:
    path: /es/benefits/benefit-details/5958
    selector: '[id="main"]'

  BID-5959:
    path: /benefits/benefit-details/5959
    selector: '[id="main"]'
  BID-5959-ES:
    path: /es/benefits/benefit-details/5959
    selector: '[id="main"]'

  BID-5962:
    path: /benefits/benefit-details/5962
    selector: '[id="main"]'
  BID-5962-ES:
    path: /es/benefits/benefit-details/5962
    selector: '[id="main"]'

  BID-5963:
    path: /benefits/benefit-details/5963
    selector: '[id="main"]'
  BID-5963-ES:
    path: /es/benefits/benefit-details/5963
    selector: '[id="main"]'

  BID-5964:
    path: /benefits/benefit-details/5964
    selector: '[id="main"]'
  BID-5964-ES:
    path: /es/benefits/benefit-details/5964
    selector: '[id="main"]'

  BID-5965:
    path: /benefits/benefit-details/5965
    selector: '[id="main"]'
  BID-5965-ES:
    path: /es/benefits/benefit-details/5965
    selector: '[id="main"]'

  BID-5971:
    path: /benefits/benefit-details/5971
    selector: '[id="main"]'
  BID-5971-ES:
    path: /es/benefits/benefit-details/5971
    selector: '[id="main"]'

  BID-5972:
    path: /benefits/benefit-details/5972
    selector: '[id="main"]'
  BID-5972-ES:
    path: /es/benefits/benefit-details/5972
    selector: '[id="main"]'

  BID-5973:
    path: /benefits/benefit-details/5973
    selector: '[id="main"]'
  BID-5973-ES:
    path: /es/benefits/benefit-details/5973
    selector: '[id="main"]'

  BID-5975:
    path: /benefits/benefit-details/5975
    selector: '[id="main"]'
  BID-5975-ES:
    path: /es/benefits/benefit-details/5975
    selector: '[id="main"]'

  BID-5976:
    path: /benefits/benefit-details/5976
    selector: '[id="main"]'
  BID-5976-ES:
    path: /es/benefits/benefit-details/5976
    selector: '[id="main"]'

  BID-5977:
    path: /benefits/benefit-details/5977
    selector: '[id="main"]'
  BID-5977-ES:
    path: /es/benefits/benefit-details/5977
    selector: '[id="main"]'

  BID-5978:
    path: /benefits/benefit-details/5978
    selector: '[id="main"]'
  BID-5978-ES:
    path: /es/benefits/benefit-details/5978
    selector: '[id="main"]'

  BID-5979:
    path: /benefits/benefit-details/5979
    selector: '[id="main"]'
  BID-5979-ES:
    path: /es/benefits/benefit-details/5979
    selector: '[id="main"]'

  BID-5980:
    path: /benefits/benefit-details/5980
    selector: '[id="main"]'
  BID-5980-ES:
    path: /es/benefits/benefit-details/5980
    selector: '[id="main"]'

  BID-5981:
    path: /benefits/benefit-details/5981
    selector: '[id="main"]'
  BID-5981-ES:
    path: /es/benefits/benefit-details/5981
    selector: '[id="main"]'

  BID-5982:
    path: /benefits/benefit-details/5982
    selector: '[id="main"]'
  BID-5982-ES:
    path: /es/benefits/benefit-details/5982
    selector: '[id="main"]'

  BID-5983:
    path: /benefits/benefit-details/5983
    selector: '[id="main"]'
  BID-5983-ES:
    path: /es/benefits/benefit-details/5983
    selector: '[id="main"]'

  BID-5984:
    path: /benefits/benefit-details/5984
    selector: '[id="main"]'
  BID-5984-ES:
    path: /es/benefits/benefit-details/5984
    selector: '[id="main"]'

  BID-5985:
    path: /benefits/benefit-details/5985
    selector: '[id="main"]'
  BID-5985-ES:
    path: /es/benefits/benefit-details/5985
    selector: '[id="main"]'

  BID-5986:
    path: /benefits/benefit-details/5986
    selector: '[id="main"]'
  BID-5986-ES:
    path: /es/benefits/benefit-details/5986
    selector: '[id="main"]'

  BID-5987:
    path: /benefits/benefit-details/5987
    selector: '[id="main"]'
  BID-5987-ES:
    path: /es/benefits/benefit-details/5987
    selector: '[id="main"]'

  BID-5988:
    path: /benefits/benefit-details/5988
    selector: '[id="main"]'
  BID-5988-ES:
    path: /es/benefits/benefit-details/5988
    selector: '[id="main"]'

  BID-5989:
    path: /benefits/benefit-details/5989
    selector: '[id="main"]'
  BID-5989-ES:
    path: /es/benefits/benefit-details/5989
    selector: '[id="main"]'

  BID-5990:
    path: /benefits/benefit-details/5990
    selector: '[id="main"]'
  BID-5990-ES:
    path: /es/benefits/benefit-details/5990
    selector: '[id="main"]'

  BID-5991:
    path: /benefits/benefit-details/5991
    selector: '[id="main"]'
  BID-5991-ES:
    path: /es/benefits/benefit-details/5991
    selector: '[id="main"]'

  BID-5992:
    path: /benefits/benefit-details/5992
    selector: '[id="main"]'
  BID-5992-ES:
    path: /es/benefits/benefit-details/5992
    selector: '[id="main"]'

  BID-5993:
    path: /benefits/benefit-details/5993
    selector: '[id="main"]'
  BID-5993-ES:
    path: /es/benefits/benefit-details/5993
    selector: '[id="main"]'

  BID-5994:
    path: /benefits/benefit-details/5994
    selector: '[id="main"]'
  BID-5994-ES:
    path: /es/benefits/benefit-details/5994
    selector: '[id="main"]'

  BID-5995:
    path: /benefits/benefit-details/5995
    selector: '[id="main"]'
  BID-5995-ES:
    path: /es/benefits/benefit-details/5995
    selector: '[id="main"]'

  BID-5996:
    path: /benefits/benefit-details/5996
    selector: '[id="main"]'
  BID-5996-ES:
    path: /es/benefits/benefit-details/5996
    selector: '[id="main"]'

  BID-5997:
    path: /benefits/benefit-details/5997
    selector: '[id="main"]'
  BID-5997-ES:
    path: /es/benefits/benefit-details/5997
    selector: '[id="main"]'

  BID-5998:
    path: /benefits/benefit-details/5998
    selector: '[id="main"]'
  BID-5998-ES:
    path: /es/benefits/benefit-details/5998
    selector: '[id="main"]'

  BID-5999:
    path: /benefits/benefit-details/5999
    selector: '[id="main"]'
  BID-5999-ES:
    path: /es/benefits/benefit-details/5999
    selector: '[id="main"]'

  BID-6000:
    path: /benefits/benefit-details/6000
    selector: '[id="main"]'
  BID-6000-ES:
    path: /es/benefits/benefit-details/6000
    selector: '[id="main"]'

  BID-6001:
    path: /benefits/benefit-details/6001
    selector: '[id="main"]'
  BID-6001-ES:
    path: /es/benefits/benefit-details/6001
    selector: '[id="main"]'

  BID-6002:
    path: /benefits/benefit-details/6002
    selector: '[id="main"]'
  BID-6002-ES:
    path: /es/benefits/benefit-details/6002
    selector: '[id="main"]'

  BID-6003:
    path: /benefits/benefit-details/6003
    selector: '[id="main"]'
  BID-6003-ES:
    path: /es/benefits/benefit-details/6003
    selector: '[id="main"]'

  BID-6004:
    path: /benefits/benefit-details/6004
    selector: '[id="main"]'
  BID-6004-ES:
    path: /es/benefits/benefit-details/6004
    selector: '[id="main"]'

  BID-6005:
    path: /benefits/benefit-details/6005
    selector: '[id="main"]'
  BID-6005-ES:
    path: /es/benefits/benefit-details/6005
    selector: '[id="main"]'

  BID-6006:
    path: /benefits/benefit-details/6006
    selector: '[id="main"]'
  BID-6006-ES:
    path: /es/benefits/benefit-details/6006
    selector: '[id="main"]'

  BID-6007:
    path: /benefits/benefit-details/6007
    selector: '[id="main"]'
  BID-6007-ES:
    path: /es/benefits/benefit-details/6007
    selector: '[id="main"]'

  BID-6009:
    path: /benefits/benefit-details/6009
    selector: '[id="main"]'
  BID-6009-ES:
    path: /es/benefits/benefit-details/6009
    selector: '[id="main"]'

  BID-6010:
    path: /benefits/benefit-details/6010
    selector: '[id="main"]'
  BID-6010-ES:
    path: /es/benefits/benefit-details/6010
    selector: '[id="main"]'

  BID-6011:
    path: /benefits/benefit-details/6011
    selector: '[id="main"]'
  BID-6011-ES:
    path: /es/benefits/benefit-details/6011
    selector: '[id="main"]'

  BID-6012:
    path: /benefits/benefit-details/6012
    selector: '[id="main"]'
  BID-6012-ES:
    path: /es/benefits/benefit-details/6012
    selector: '[id="main"]'

  BID-6013:
    path: /benefits/benefit-details/6013
    selector: '[id="main"]'
  BID-6013-ES:
    path: /es/benefits/benefit-details/6013
    selector: '[id="main"]'

  BID-6014:
    path: /benefits/benefit-details/6014
    selector: '[id="main"]'
  BID-6014-ES:
    path: /es/benefits/benefit-details/6014
    selector: '[id="main"]'

  BID-6015:
    path: /benefits/benefit-details/6015
    selector: '[id="main"]'
  BID-6015-ES:
    path: /es/benefits/benefit-details/6015
    selector: '[id="main"]'

  BID-6016:
    path: /benefits/benefit-details/6016
    selector: '[id="main"]'
  BID-6016-ES:
    path: /es/benefits/benefit-details/6016
    selector: '[id="main"]'

  BID-6017:
    path: /benefits/benefit-details/6017
    selector: '[id="main"]'
  BID-6017-ES:
    path: /es/benefits/benefit-details/6017
    selector: '[id="main"]'

  BID-6018:
    path: /benefits/benefit-details/6018
    selector: '[id="main"]'
  BID-6018-ES:
    path: /es/benefits/benefit-details/6018
    selector: '[id="main"]'

  BID-6019:
    path: /benefits/benefit-details/6019
    selector: '[id="main"]'
  BID-6019-ES:
    path: /es/benefits/benefit-details/6019
    selector: '[id="main"]'

  BID-6020:
    path: /benefits/benefit-details/6020
    selector: '[id="main"]'
  BID-6020-ES:
    path: /es/benefits/benefit-details/6020
    selector: '[id="main"]'

  BID-6021:
    path: /benefits/benefit-details/6021
    selector: '[id="main"]'
  BID-6021-ES:
    path: /es/benefits/benefit-details/6021
    selector: '[id="main"]'

  BID-6022:
    path: /benefits/benefit-details/6022
    selector: '[id="main"]'
  BID-6022-ES:
    path: /es/benefits/benefit-details/6022
    selector: '[id="main"]'

  BID-6023:
    path: /benefits/benefit-details/6023
    selector: '[id="main"]'
  BID-6023-ES:
    path: /es/benefits/benefit-details/6023
    selector: '[id="main"]'

  BID-6024:
    path: /benefits/benefit-details/6024
    selector: '[id="main"]'
  BID-6024-ES:
    path: /es/benefits/benefit-details/6024
    selector: '[id="main"]'

  BID-6025:
    path: /benefits/benefit-details/6025
    selector: '[id="main"]'
  BID-6025-ES:
    path: /es/benefits/benefit-details/6025
    selector: '[id="main"]'

  BID-6026:
    path: /benefits/benefit-details/6026
    selector: '[id="main"]'
  BID-6026-ES:
    path: /es/benefits/benefit-details/6026
    selector: '[id="main"]'

  BID-6027:
    path: /benefits/benefit-details/6027
    selector: '[id="main"]'
  BID-6027-ES:
    path: /es/benefits/benefit-details/6027
    selector: '[id="main"]'

  BID-6028:
    path: /benefits/benefit-details/6028
    selector: '[id="main"]'
  BID-6028-ES:
    path: /es/benefits/benefit-details/6028
    selector: '[id="main"]'

  BID-6029:
    path: /benefits/benefit-details/6029
    selector: '[id="main"]'
  BID-6029-ES:
    path: /es/benefits/benefit-details/6029
    selector: '[id="main"]'

  BID-6030:
    path: /benefits/benefit-details/6030
    selector: '[id="main"]'
  BID-6030-ES:
    path: /es/benefits/benefit-details/6030
    selector: '[id="main"]'

  BID-6031:
    path: /benefits/benefit-details/6031
    selector: '[id="main"]'
  BID-6031-ES:
    path: /es/benefits/benefit-details/6031
    selector: '[id="main"]'

  BID-6032:
    path: /benefits/benefit-details/6032
    selector: '[id="main"]'
  BID-6032-ES:
    path: /es/benefits/benefit-details/6032
    selector: '[id="main"]'

  BID-6033:
    path: /benefits/benefit-details/6033
    selector: '[id="main"]'
  BID-6033-ES:
    path: /es/benefits/benefit-details/6033
    selector: '[id="main"]'

  BID-6034:
    path: /benefits/benefit-details/6034
    selector: '[id="main"]'
  BID-6034-ES:
    path: /es/benefits/benefit-details/6034
    selector: '[id="main"]'

  BID-6035:
    path: /benefits/benefit-details/6035
    selector: '[id="main"]'
  BID-6035-ES:
    path: /es/benefits/benefit-details/6035
    selector: '[id="main"]'

  BID-6036:
    path: /benefits/benefit-details/6036
    selector: '[id="main"]'
  BID-6036-ES:
    path: /es/benefits/benefit-details/6036
    selector: '[id="main"]'

  BID-6037:
    path: /benefits/benefit-details/6037
    selector: '[id="main"]'
  BID-6037-ES:
    path: /es/benefits/benefit-details/6037
    selector: '[id="main"]'

  BID-6038:
    path: /benefits/benefit-details/6038
    selector: '[id="main"]'
  BID-6038-ES:
    path: /es/benefits/benefit-details/6038
    selector: '[id="main"]'

  BID-6039:
    path: /benefits/benefit-details/6039
    selector: '[id="main"]'
  BID-6039-ES:
    path: /es/benefits/benefit-details/6039
    selector: '[id="main"]'



# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "casperjs"

phantomjs_options: --ignore-ssl-errors=yes

################################################################

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--casper.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  #- 450x650
  - 1280

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
#before_capture: 'javascript/disable_javascript--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots/capture/BG/bids/part10'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  #template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
  



