##############################################################
##############################################################
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# run with "wraith capture configs/BG/bids/All-BIDs-part7.yaml"
#
##############################################################
##############################################################

# (required) The domains to take screenshots of.
domains:
  prod: "https://www.benefits.gov"
  staging: "https://staging.benefits.gov"

# (required) The paths to capture. All paths should exist for both of the domains specified above.

paths:


BID-1768:
    path: /benefits/benefit-details/1768
    selector: '[id="main"]'
  BID-1768-ES:
    path: /es/benefits/benefit-details/1768
    selector: '[id="main"]'

  BID-1769:
    path: /benefits/benefit-details/1769
    selector: '[id="main"]'
  BID-1769-ES:
    path: /es/benefits/benefit-details/1769
    selector: '[id="main"]'

  BID-1770:
    path: /benefits/benefit-details/1770
    selector: '[id="main"]'
  BID-1770-ES:
    path: /es/benefits/benefit-details/1770
    selector: '[id="main"]'

  BID-1771:
    path: /benefits/benefit-details/1771
    selector: '[id="main"]'
  BID-1771-ES:
    path: /es/benefits/benefit-details/1771
    selector: '[id="main"]'

  BID-1772:
    path: /benefits/benefit-details/1772
    selector: '[id="main"]'
  BID-1772-ES:
    path: /es/benefits/benefit-details/1772
    selector: '[id="main"]'

  BID-1773:
    path: /benefits/benefit-details/1773
    selector: '[id="main"]'
  BID-1773-ES:
    path: /es/benefits/benefit-details/1773
    selector: '[id="main"]'

  BID-1774:
    path: /benefits/benefit-details/1774
    selector: '[id="main"]'
  BID-1774-ES:
    path: /es/benefits/benefit-details/1774
    selector: '[id="main"]'

  BID-1775:
    path: /benefits/benefit-details/1775
    selector: '[id="main"]'
  BID-1775-ES:
    path: /es/benefits/benefit-details/1775
    selector: '[id="main"]'

  BID-1777:
    path: /benefits/benefit-details/1777
    selector: '[id="main"]'
  BID-1777-ES:
    path: /es/benefits/benefit-details/1777
    selector: '[id="main"]'

  BID-1793:
    path: /benefits/benefit-details/1793
    selector: '[id="main"]'
  BID-1793-ES:
    path: /es/benefits/benefit-details/1793
    selector: '[id="main"]'

  BID-1800:
    path: /benefits/benefit-details/1800
    selector: '[id="main"]'
  BID-1800-ES:
    path: /es/benefits/benefit-details/1800
    selector: '[id="main"]'

  BID-1801:
    path: /benefits/benefit-details/1801
    selector: '[id="main"]'
  BID-1801-ES:
    path: /es/benefits/benefit-details/1801
    selector: '[id="main"]'

  BID-1809:
    path: /benefits/benefit-details/1809
    selector: '[id="main"]'
  BID-1809-ES:
    path: /es/benefits/benefit-details/1809
    selector: '[id="main"]'

  BID-1810:
    path: /benefits/benefit-details/1810
    selector: '[id="main"]'
  BID-1810-ES:
    path: /es/benefits/benefit-details/1810
    selector: '[id="main"]'

  BID-1821:
    path: /benefits/benefit-details/1821
    selector: '[id="main"]'
  BID-1821-ES:
    path: /es/benefits/benefit-details/1821
    selector: '[id="main"]'

  BID-1822:
    path: /benefits/benefit-details/1822
    selector: '[id="main"]'
  BID-1822-ES:
    path: /es/benefits/benefit-details/1822
    selector: '[id="main"]'

  BID-1823:
    path: /benefits/benefit-details/1823
    selector: '[id="main"]'
  BID-1823-ES:
    path: /es/benefits/benefit-details/1823
    selector: '[id="main"]'

  BID-1824:
    path: /benefits/benefit-details/1824
    selector: '[id="main"]'
  BID-1824-ES:
    path: /es/benefits/benefit-details/1824
    selector: '[id="main"]'

  BID-1825:
    path: /benefits/benefit-details/1825
    selector: '[id="main"]'
  BID-1825-ES:
    path: /es/benefits/benefit-details/1825
    selector: '[id="main"]'

  BID-1826:
    path: /benefits/benefit-details/1826
    selector: '[id="main"]'
  BID-1826-ES:
    path: /es/benefits/benefit-details/1826
    selector: '[id="main"]'

  BID-1827:
    path: /benefits/benefit-details/1827
    selector: '[id="main"]'
  BID-1827-ES:
    path: /es/benefits/benefit-details/1827
    selector: '[id="main"]'

  BID-1828:
    path: /benefits/benefit-details/1828
    selector: '[id="main"]'
  BID-1828-ES:
    path: /es/benefits/benefit-details/1828
    selector: '[id="main"]'

  BID-1831:
    path: /benefits/benefit-details/1831
    selector: '[id="main"]'
  BID-1831-ES:
    path: /es/benefits/benefit-details/1831
    selector: '[id="main"]'

  BID-1841:
    path: /benefits/benefit-details/1841
    selector: '[id="main"]'
  BID-1841-ES:
    path: /es/benefits/benefit-details/1841
    selector: '[id="main"]'

  BID-1842:
    path: /benefits/benefit-details/1842
    selector: '[id="main"]'
  BID-1842-ES:
    path: /es/benefits/benefit-details/1842
    selector: '[id="main"]'

  BID-1843:
    path: /benefits/benefit-details/1843
    selector: '[id="main"]'
  BID-1843-ES:
    path: /es/benefits/benefit-details/1843
    selector: '[id="main"]'

  BID-1844:
    path: /benefits/benefit-details/1844
    selector: '[id="main"]'
  BID-1844-ES:
    path: /es/benefits/benefit-details/1844
    selector: '[id="main"]'

  BID-1845:
    path: /benefits/benefit-details/1845
    selector: '[id="main"]'
  BID-1845-ES:
    path: /es/benefits/benefit-details/1845
    selector: '[id="main"]'

  BID-1846:
    path: /benefits/benefit-details/1846
    selector: '[id="main"]'
  BID-1846-ES:
    path: /es/benefits/benefit-details/1846
    selector: '[id="main"]'

  BID-1847:
    path: /benefits/benefit-details/1847
    selector: '[id="main"]'
  BID-1847-ES:
    path: /es/benefits/benefit-details/1847
    selector: '[id="main"]'

  BID-1848:
    path: /benefits/benefit-details/1848
    selector: '[id="main"]'
  BID-1848-ES:
    path: /es/benefits/benefit-details/1848
    selector: '[id="main"]'

  BID-1849:
    path: /benefits/benefit-details/1849
    selector: '[id="main"]'
  BID-1849-ES:
    path: /es/benefits/benefit-details/1849
    selector: '[id="main"]'

  BID-1850:
    path: /benefits/benefit-details/1850
    selector: '[id="main"]'
  BID-1850-ES:
    path: /es/benefits/benefit-details/1850
    selector: '[id="main"]'

  BID-1851:
    path: /benefits/benefit-details/1851
    selector: '[id="main"]'
  BID-1851-ES:
    path: /es/benefits/benefit-details/1851
    selector: '[id="main"]'

  BID-1853:
    path: /benefits/benefit-details/1853
    selector: '[id="main"]'
  BID-1853-ES:
    path: /es/benefits/benefit-details/1853
    selector: '[id="main"]'

  BID-1854:
    path: /benefits/benefit-details/1854
    selector: '[id="main"]'
  BID-1854-ES:
    path: /es/benefits/benefit-details/1854
    selector: '[id="main"]'

  BID-1855:
    path: /benefits/benefit-details/1855
    selector: '[id="main"]'
  BID-1855-ES:
    path: /es/benefits/benefit-details/1855
    selector: '[id="main"]'

  BID-1856:
    path: /benefits/benefit-details/1856
    selector: '[id="main"]'
  BID-1856-ES:
    path: /es/benefits/benefit-details/1856
    selector: '[id="main"]'

  BID-1857:
    path: /benefits/benefit-details/1857
    selector: '[id="main"]'
  BID-1857-ES:
    path: /es/benefits/benefit-details/1857
    selector: '[id="main"]'

  BID-1858:
    path: /benefits/benefit-details/1858
    selector: '[id="main"]'
  BID-1858-ES:
    path: /es/benefits/benefit-details/1858
    selector: '[id="main"]'

  BID-1859:
    path: /benefits/benefit-details/1859
    selector: '[id="main"]'
  BID-1859-ES:
    path: /es/benefits/benefit-details/1859
    selector: '[id="main"]'

  BID-1860:
    path: /benefits/benefit-details/1860
    selector: '[id="main"]'
  BID-1860-ES:
    path: /es/benefits/benefit-details/1860
    selector: '[id="main"]'

  BID-1862:
    path: /benefits/benefit-details/1862
    selector: '[id="main"]'
  BID-1862-ES:
    path: /es/benefits/benefit-details/1862
    selector: '[id="main"]'

  BID-1863:
    path: /benefits/benefit-details/1863
    selector: '[id="main"]'
  BID-1863-ES:
    path: /es/benefits/benefit-details/1863
    selector: '[id="main"]'

  BID-1864:
    path: /benefits/benefit-details/1864
    selector: '[id="main"]'
  BID-1864-ES:
    path: /es/benefits/benefit-details/1864
    selector: '[id="main"]'

  BID-1865:
    path: /benefits/benefit-details/1865
    selector: '[id="main"]'
  BID-1865-ES:
    path: /es/benefits/benefit-details/1865
    selector: '[id="main"]'

  BID-1866:
    path: /benefits/benefit-details/1866
    selector: '[id="main"]'
  BID-1866-ES:
    path: /es/benefits/benefit-details/1866
    selector: '[id="main"]'

  BID-1867:
    path: /benefits/benefit-details/1867
    selector: '[id="main"]'
  BID-1867-ES:
    path: /es/benefits/benefit-details/1867
    selector: '[id="main"]'

  BID-1868:
    path: /benefits/benefit-details/1868
    selector: '[id="main"]'
  BID-1868-ES:
    path: /es/benefits/benefit-details/1868
    selector: '[id="main"]'

  BID-1869:
    path: /benefits/benefit-details/1869
    selector: '[id="main"]'
  BID-1869-ES:
    path: /es/benefits/benefit-details/1869
    selector: '[id="main"]'

  BID-1871:
    path: /benefits/benefit-details/1871
    selector: '[id="main"]'
  BID-1871-ES:
    path: /es/benefits/benefit-details/1871
    selector: '[id="main"]'

  BID-1872:
    path: /benefits/benefit-details/1872
    selector: '[id="main"]'
  BID-1872-ES:
    path: /es/benefits/benefit-details/1872
    selector: '[id="main"]'

  BID-1873:
    path: /benefits/benefit-details/1873
    selector: '[id="main"]'
  BID-1873-ES:
    path: /es/benefits/benefit-details/1873
    selector: '[id="main"]'

  BID-1874:
    path: /benefits/benefit-details/1874
    selector: '[id="main"]'
  BID-1874-ES:
    path: /es/benefits/benefit-details/1874
    selector: '[id="main"]'

  BID-1875:
    path: /benefits/benefit-details/1875
    selector: '[id="main"]'
  BID-1875-ES:
    path: /es/benefits/benefit-details/1875
    selector: '[id="main"]'

  BID-1878:
    path: /benefits/benefit-details/1878
    selector: '[id="main"]'
  BID-1878-ES:
    path: /es/benefits/benefit-details/1878
    selector: '[id="main"]'

  BID-1879:
    path: /benefits/benefit-details/1879
    selector: '[id="main"]'
  BID-1879-ES:
    path: /es/benefits/benefit-details/1879
    selector: '[id="main"]'

  BID-1880:
    path: /benefits/benefit-details/1880
    selector: '[id="main"]'
  BID-1880-ES:
    path: /es/benefits/benefit-details/1880
    selector: '[id="main"]'

  BID-1881:
    path: /benefits/benefit-details/1881
    selector: '[id="main"]'
  BID-1881-ES:
    path: /es/benefits/benefit-details/1881
    selector: '[id="main"]'

  BID-1882:
    path: /benefits/benefit-details/1882
    selector: '[id="main"]'
  BID-1882-ES:
    path: /es/benefits/benefit-details/1882
    selector: '[id="main"]'

  BID-1883:
    path: /benefits/benefit-details/1883
    selector: '[id="main"]'
  BID-1883-ES:
    path: /es/benefits/benefit-details/1883
    selector: '[id="main"]'

  BID-1884:
    path: /benefits/benefit-details/1884
    selector: '[id="main"]'
  BID-1884-ES:
    path: /es/benefits/benefit-details/1884
    selector: '[id="main"]'

  BID-1885:
    path: /benefits/benefit-details/1885
    selector: '[id="main"]'
  BID-1885-ES:
    path: /es/benefits/benefit-details/1885
    selector: '[id="main"]'

  BID-1886:
    path: /benefits/benefit-details/1886
    selector: '[id="main"]'
  BID-1886-ES:
    path: /es/benefits/benefit-details/1886
    selector: '[id="main"]'

  BID-1887:
    path: /benefits/benefit-details/1887
    selector: '[id="main"]'
  BID-1887-ES:
    path: /es/benefits/benefit-details/1887
    selector: '[id="main"]'

  BID-1888:
    path: /benefits/benefit-details/1888
    selector: '[id="main"]'
  BID-1888-ES:
    path: /es/benefits/benefit-details/1888
    selector: '[id="main"]'

  BID-1895:
    path: /benefits/benefit-details/1895
    selector: '[id="main"]'
  BID-1895-ES:
    path: /es/benefits/benefit-details/1895
    selector: '[id="main"]'

  BID-1896:
    path: /benefits/benefit-details/1896
    selector: '[id="main"]'
  BID-1896-ES:
    path: /es/benefits/benefit-details/1896
    selector: '[id="main"]'

  BID-1897:
    path: /benefits/benefit-details/1897
    selector: '[id="main"]'
  BID-1897-ES:
    path: /es/benefits/benefit-details/1897
    selector: '[id="main"]'

  BID-1898:
    path: /benefits/benefit-details/1898
    selector: '[id="main"]'
  BID-1898-ES:
    path: /es/benefits/benefit-details/1898
    selector: '[id="main"]'

  BID-1899:
    path: /benefits/benefit-details/1899
    selector: '[id="main"]'
  BID-1899-ES:
    path: /es/benefits/benefit-details/1899
    selector: '[id="main"]'

  BID-1900:
    path: /benefits/benefit-details/1900
    selector: '[id="main"]'
  BID-1900-ES:
    path: /es/benefits/benefit-details/1900
    selector: '[id="main"]'

  BID-1901:
    path: /benefits/benefit-details/1901
    selector: '[id="main"]'
  BID-1901-ES:
    path: /es/benefits/benefit-details/1901
    selector: '[id="main"]'

  BID-1902:
    path: /benefits/benefit-details/1902
    selector: '[id="main"]'
  BID-1902-ES:
    path: /es/benefits/benefit-details/1902
    selector: '[id="main"]'

  BID-1903:
    path: /benefits/benefit-details/1903
    selector: '[id="main"]'
  BID-1903-ES:
    path: /es/benefits/benefit-details/1903
    selector: '[id="main"]'

  BID-1904:
    path: /benefits/benefit-details/1904
    selector: '[id="main"]'
  BID-1904-ES:
    path: /es/benefits/benefit-details/1904
    selector: '[id="main"]'

  BID-1905:
    path: /benefits/benefit-details/1905
    selector: '[id="main"]'
  BID-1905-ES:
    path: /es/benefits/benefit-details/1905
    selector: '[id="main"]'

  BID-1906:
    path: /benefits/benefit-details/1906
    selector: '[id="main"]'
  BID-1906-ES:
    path: /es/benefits/benefit-details/1906
    selector: '[id="main"]'

  BID-1907:
    path: /benefits/benefit-details/1907
    selector: '[id="main"]'
  BID-1907-ES:
    path: /es/benefits/benefit-details/1907
    selector: '[id="main"]'

  BID-1908:
    path: /benefits/benefit-details/1908
    selector: '[id="main"]'
  BID-1908-ES:
    path: /es/benefits/benefit-details/1908
    selector: '[id="main"]'

  BID-1909:
    path: /benefits/benefit-details/1909
    selector: '[id="main"]'
  BID-1909-ES:
    path: /es/benefits/benefit-details/1909
    selector: '[id="main"]'

  BID-1910:
    path: /benefits/benefit-details/1910
    selector: '[id="main"]'
  BID-1910-ES:
    path: /es/benefits/benefit-details/1910
    selector: '[id="main"]'

  BID-1911:
    path: /benefits/benefit-details/1911
    selector: '[id="main"]'
  BID-1911-ES:
    path: /es/benefits/benefit-details/1911
    selector: '[id="main"]'

  BID-1912:
    path: /benefits/benefit-details/1912
    selector: '[id="main"]'
  BID-1912-ES:
    path: /es/benefits/benefit-details/1912
    selector: '[id="main"]'

  BID-1913:
    path: /benefits/benefit-details/1913
    selector: '[id="main"]'
  BID-1913-ES:
    path: /es/benefits/benefit-details/1913
    selector: '[id="main"]'

  BID-1914:
    path: /benefits/benefit-details/1914
    selector: '[id="main"]'
  BID-1914-ES:
    path: /es/benefits/benefit-details/1914
    selector: '[id="main"]'

  BID-1915:
    path: /benefits/benefit-details/1915
    selector: '[id="main"]'
  BID-1915-ES:
    path: /es/benefits/benefit-details/1915
    selector: '[id="main"]'

  BID-1916:
    path: /benefits/benefit-details/1916
    selector: '[id="main"]'
  BID-1916-ES:
    path: /es/benefits/benefit-details/1916
    selector: '[id="main"]'

  BID-1917:
    path: /benefits/benefit-details/1917
    selector: '[id="main"]'
  BID-1917-ES:
    path: /es/benefits/benefit-details/1917
    selector: '[id="main"]'

  BID-1918:
    path: /benefits/benefit-details/1918
    selector: '[id="main"]'
  BID-1918-ES:
    path: /es/benefits/benefit-details/1918
    selector: '[id="main"]'

  BID-1919:
    path: /benefits/benefit-details/1919
    selector: '[id="main"]'
  BID-1919-ES:
    path: /es/benefits/benefit-details/1919
    selector: '[id="main"]'

  BID-1920:
    path: /benefits/benefit-details/1920
    selector: '[id="main"]'
  BID-1920-ES:
    path: /es/benefits/benefit-details/1920
    selector: '[id="main"]'

  BID-1921:
    path: /benefits/benefit-details/1921
    selector: '[id="main"]'
  BID-1921-ES:
    path: /es/benefits/benefit-details/1921
    selector: '[id="main"]'

  BID-1923:
    path: /benefits/benefit-details/1923
    selector: '[id="main"]'
  BID-1923-ES:
    path: /es/benefits/benefit-details/1923
    selector: '[id="main"]'

  BID-1924:
    path: /benefits/benefit-details/1924
    selector: '[id="main"]'
  BID-1924-ES:
    path: /es/benefits/benefit-details/1924
    selector: '[id="main"]'

  BID-1926:
    path: /benefits/benefit-details/1926
    selector: '[id="main"]'
  BID-1926-ES:
    path: /es/benefits/benefit-details/1926
    selector: '[id="main"]'

  BID-1927:
    path: /benefits/benefit-details/1927
    selector: '[id="main"]'
  BID-1927-ES:
    path: /es/benefits/benefit-details/1927
    selector: '[id="main"]'

  BID-1928:
    path: /benefits/benefit-details/1928
    selector: '[id="main"]'
  BID-1928-ES:
    path: /es/benefits/benefit-details/1928
    selector: '[id="main"]'

  BID-1929:
    path: /benefits/benefit-details/1929
    selector: '[id="main"]'
  BID-1929-ES:
    path: /es/benefits/benefit-details/1929
    selector: '[id="main"]'

  BID-1930:
    path: /benefits/benefit-details/1930
    selector: '[id="main"]'
  BID-1930-ES:
    path: /es/benefits/benefit-details/1930
    selector: '[id="main"]'



# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "casperjs"

phantomjs_options: --ignore-ssl-errors=yes

################################################################

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--casper.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  #- 450x650
  - 1280

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
#before_capture: 'javascript/disable_javascript--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots/capture/BG/bids/part7'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  #template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
  



