##############################################################
##############################################################
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# run with "wraith capture configs/BG/bids/All-BIDs-part4.yaml"
#
##############################################################
##############################################################

# (required) The domains to take screenshots of.
domains:
  prod: "https://www.benefits.gov"
  staging: "https://staging.benefits.gov"

# (required) The paths to capture. All paths should exist for both of the domains specified above.

paths:


  BID-1252:
    path: /benefits/benefit-details/1252
    selector: '[id="main"]'
  BID-1252-ES:
    path: /es/benefits/benefit-details/1252
    selector: '[id="main"]'

  BID-1254:
    path: /benefits/benefit-details/1254
    selector: '[id="main"]'
  BID-1254-ES:
    path: /es/benefits/benefit-details/1254
    selector: '[id="main"]'

  BID-1255:
    path: /benefits/benefit-details/1255
    selector: '[id="main"]'
  BID-1255-ES:
    path: /es/benefits/benefit-details/1255
    selector: '[id="main"]'

  BID-1256:
    path: /benefits/benefit-details/1256
    selector: '[id="main"]'
  BID-1256-ES:
    path: /es/benefits/benefit-details/1256
    selector: '[id="main"]'

  BID-1260:
    path: /benefits/benefit-details/1260
    selector: '[id="main"]'
  BID-1260-ES:
    path: /es/benefits/benefit-details/1260
    selector: '[id="main"]'

  BID-1264:
    path: /benefits/benefit-details/1264
    selector: '[id="main"]'
  BID-1264-ES:
    path: /es/benefits/benefit-details/1264
    selector: '[id="main"]'

  BID-1265:
    path: /benefits/benefit-details/1265
    selector: '[id="main"]'
  BID-1265-ES:
    path: /es/benefits/benefit-details/1265
    selector: '[id="main"]'

  BID-1268:
    path: /benefits/benefit-details/1268
    selector: '[id="main"]'
  BID-1268-ES:
    path: /es/benefits/benefit-details/1268
    selector: '[id="main"]'

  BID-1270:
    path: /benefits/benefit-details/1270
    selector: '[id="main"]'
  BID-1270-ES:
    path: /es/benefits/benefit-details/1270
    selector: '[id="main"]'

  BID-1271:
    path: /benefits/benefit-details/1271
    selector: '[id="main"]'
  BID-1271-ES:
    path: /es/benefits/benefit-details/1271
    selector: '[id="main"]'

  BID-1272:
    path: /benefits/benefit-details/1272
    selector: '[id="main"]'
  BID-1272-ES:
    path: /es/benefits/benefit-details/1272
    selector: '[id="main"]'

  BID-1276:
    path: /benefits/benefit-details/1276
    selector: '[id="main"]'
  BID-1276-ES:
    path: /es/benefits/benefit-details/1276
    selector: '[id="main"]'

  BID-1277:
    path: /benefits/benefit-details/1277
    selector: '[id="main"]'
  BID-1277-ES:
    path: /es/benefits/benefit-details/1277
    selector: '[id="main"]'

  BID-1278:
    path: /benefits/benefit-details/1278
    selector: '[id="main"]'
  BID-1278-ES:
    path: /es/benefits/benefit-details/1278
    selector: '[id="main"]'

  BID-1280:
    path: /benefits/benefit-details/1280
    selector: '[id="main"]'
  BID-1280-ES:
    path: /es/benefits/benefit-details/1280
    selector: '[id="main"]'

  BID-1281:
    path: /benefits/benefit-details/1281
    selector: '[id="main"]'
  BID-1281-ES:
    path: /es/benefits/benefit-details/1281
    selector: '[id="main"]'

  BID-1282:
    path: /benefits/benefit-details/1282
    selector: '[id="main"]'
  BID-1282-ES:
    path: /es/benefits/benefit-details/1282
    selector: '[id="main"]'

  BID-1283:
    path: /benefits/benefit-details/1283
    selector: '[id="main"]'
  BID-1283-ES:
    path: /es/benefits/benefit-details/1283
    selector: '[id="main"]'

  BID-1286:
    path: /benefits/benefit-details/1286
    selector: '[id="main"]'
  BID-1286-ES:
    path: /es/benefits/benefit-details/1286
    selector: '[id="main"]'

  BID-1287:
    path: /benefits/benefit-details/1287
    selector: '[id="main"]'
  BID-1287-ES:
    path: /es/benefits/benefit-details/1287
    selector: '[id="main"]'

  BID-1288:
    path: /benefits/benefit-details/1288
    selector: '[id="main"]'
  BID-1288-ES:
    path: /es/benefits/benefit-details/1288
    selector: '[id="main"]'

  BID-1292:
    path: /benefits/benefit-details/1292
    selector: '[id="main"]'
  BID-1292-ES:
    path: /es/benefits/benefit-details/1292
    selector: '[id="main"]'

  BID-1296:
    path: /benefits/benefit-details/1296
    selector: '[id="main"]'
  BID-1296-ES:
    path: /es/benefits/benefit-details/1296
    selector: '[id="main"]'

  BID-1299:
    path: /benefits/benefit-details/1299
    selector: '[id="main"]'
  BID-1299-ES:
    path: /es/benefits/benefit-details/1299
    selector: '[id="main"]'

  BID-1300:
    path: /benefits/benefit-details/1300
    selector: '[id="main"]'
  BID-1300-ES:
    path: /es/benefits/benefit-details/1300
    selector: '[id="main"]'

  BID-1302:
    path: /benefits/benefit-details/1302
    selector: '[id="main"]'
  BID-1302-ES:
    path: /es/benefits/benefit-details/1302
    selector: '[id="main"]'

  BID-1307:
    path: /benefits/benefit-details/1307
    selector: '[id="main"]'
  BID-1307-ES:
    path: /es/benefits/benefit-details/1307
    selector: '[id="main"]'

  BID-1308:
    path: /benefits/benefit-details/1308
    selector: '[id="main"]'
  BID-1308-ES:
    path: /es/benefits/benefit-details/1308
    selector: '[id="main"]'

  BID-1312:
    path: /benefits/benefit-details/1312
    selector: '[id="main"]'
  BID-1312-ES:
    path: /es/benefits/benefit-details/1312
    selector: '[id="main"]'

  BID-1313:
    path: /benefits/benefit-details/1313
    selector: '[id="main"]'
  BID-1313-ES:
    path: /es/benefits/benefit-details/1313
    selector: '[id="main"]'

  BID-1314:
    path: /benefits/benefit-details/1314
    selector: '[id="main"]'
  BID-1314-ES:
    path: /es/benefits/benefit-details/1314
    selector: '[id="main"]'

  BID-1315:
    path: /benefits/benefit-details/1315
    selector: '[id="main"]'
  BID-1315-ES:
    path: /es/benefits/benefit-details/1315
    selector: '[id="main"]'

  BID-1319:
    path: /benefits/benefit-details/1319
    selector: '[id="main"]'
  BID-1319-ES:
    path: /es/benefits/benefit-details/1319
    selector: '[id="main"]'

  BID-1320:
    path: /benefits/benefit-details/1320
    selector: '[id="main"]'
  BID-1320-ES:
    path: /es/benefits/benefit-details/1320
    selector: '[id="main"]'

  BID-1328:
    path: /benefits/benefit-details/1328
    selector: '[id="main"]'
  BID-1328-ES:
    path: /es/benefits/benefit-details/1328
    selector: '[id="main"]'

  BID-1331:
    path: /benefits/benefit-details/1331
    selector: '[id="main"]'
  BID-1331-ES:
    path: /es/benefits/benefit-details/1331
    selector: '[id="main"]'

  BID-1332:
    path: /benefits/benefit-details/1332
    selector: '[id="main"]'
  BID-1332-ES:
    path: /es/benefits/benefit-details/1332
    selector: '[id="main"]'

  BID-1333:
    path: /benefits/benefit-details/1333
    selector: '[id="main"]'
  BID-1333-ES:
    path: /es/benefits/benefit-details/1333
    selector: '[id="main"]'

  BID-1334:
    path: /benefits/benefit-details/1334
    selector: '[id="main"]'
  BID-1334-ES:
    path: /es/benefits/benefit-details/1334
    selector: '[id="main"]'

  BID-1336:
    path: /benefits/benefit-details/1336
    selector: '[id="main"]'
  BID-1336-ES:
    path: /es/benefits/benefit-details/1336
    selector: '[id="main"]'

  BID-1342:
    path: /benefits/benefit-details/1342
    selector: '[id="main"]'
  BID-1342-ES:
    path: /es/benefits/benefit-details/1342
    selector: '[id="main"]'

  BID-1344:
    path: /benefits/benefit-details/1344
    selector: '[id="main"]'
  BID-1344-ES:
    path: /es/benefits/benefit-details/1344
    selector: '[id="main"]'

  BID-1346:
    path: /benefits/benefit-details/1346
    selector: '[id="main"]'
  BID-1346-ES:
    path: /es/benefits/benefit-details/1346
    selector: '[id="main"]'

  BID-1348:
    path: /benefits/benefit-details/1348
    selector: '[id="main"]'
  BID-1348-ES:
    path: /es/benefits/benefit-details/1348
    selector: '[id="main"]'

  BID-1355:
    path: /benefits/benefit-details/1355
    selector: '[id="main"]'
  BID-1355-ES:
    path: /es/benefits/benefit-details/1355
    selector: '[id="main"]'

  BID-1356:
    path: /benefits/benefit-details/1356
    selector: '[id="main"]'
  BID-1356-ES:
    path: /es/benefits/benefit-details/1356
    selector: '[id="main"]'

  BID-1361:
    path: /benefits/benefit-details/1361
    selector: '[id="main"]'
  BID-1361-ES:
    path: /es/benefits/benefit-details/1361
    selector: '[id="main"]'

  BID-1363:
    path: /benefits/benefit-details/1363
    selector: '[id="main"]'
  BID-1363-ES:
    path: /es/benefits/benefit-details/1363
    selector: '[id="main"]'

  BID-1364:
    path: /benefits/benefit-details/1364
    selector: '[id="main"]'
  BID-1364-ES:
    path: /es/benefits/benefit-details/1364
    selector: '[id="main"]'

  BID-1368:
    path: /benefits/benefit-details/1368
    selector: '[id="main"]'
  BID-1368-ES:
    path: /es/benefits/benefit-details/1368
    selector: '[id="main"]'

  BID-1371:
    path: /benefits/benefit-details/1371
    selector: '[id="main"]'
  BID-1371-ES:
    path: /es/benefits/benefit-details/1371
    selector: '[id="main"]'

  BID-1375:
    path: /benefits/benefit-details/1375
    selector: '[id="main"]'
  BID-1375-ES:
    path: /es/benefits/benefit-details/1375
    selector: '[id="main"]'

  BID-1380:
    path: /benefits/benefit-details/1380
    selector: '[id="main"]'
  BID-1380-ES:
    path: /es/benefits/benefit-details/1380
    selector: '[id="main"]'

  BID-1386:
    path: /benefits/benefit-details/1386
    selector: '[id="main"]'
  BID-1386-ES:
    path: /es/benefits/benefit-details/1386
    selector: '[id="main"]'

  BID-1387:
    path: /benefits/benefit-details/1387
    selector: '[id="main"]'
  BID-1387-ES:
    path: /es/benefits/benefit-details/1387
    selector: '[id="main"]'

  BID-1388:
    path: /benefits/benefit-details/1388
    selector: '[id="main"]'
  BID-1388-ES:
    path: /es/benefits/benefit-details/1388
    selector: '[id="main"]'

  BID-1389:
    path: /benefits/benefit-details/1389
    selector: '[id="main"]'
  BID-1389-ES:
    path: /es/benefits/benefit-details/1389
    selector: '[id="main"]'

  BID-1390:
    path: /benefits/benefit-details/1390
    selector: '[id="main"]'
  BID-1390-ES:
    path: /es/benefits/benefit-details/1390
    selector: '[id="main"]'

  BID-1391:
    path: /benefits/benefit-details/1391
    selector: '[id="main"]'
  BID-1391-ES:
    path: /es/benefits/benefit-details/1391
    selector: '[id="main"]'

  BID-1393:
    path: /benefits/benefit-details/1393
    selector: '[id="main"]'
  BID-1393-ES:
    path: /es/benefits/benefit-details/1393
    selector: '[id="main"]'

  BID-1397:
    path: /benefits/benefit-details/1397
    selector: '[id="main"]'
  BID-1397-ES:
    path: /es/benefits/benefit-details/1397
    selector: '[id="main"]'

  BID-1410:
    path: /benefits/benefit-details/1410
    selector: '[id="main"]'
  BID-1410-ES:
    path: /es/benefits/benefit-details/1410
    selector: '[id="main"]'

  BID-1411:
    path: /benefits/benefit-details/1411
    selector: '[id="main"]'
  BID-1411-ES:
    path: /es/benefits/benefit-details/1411
    selector: '[id="main"]'

  BID-1429:
    path: /benefits/benefit-details/1429
    selector: '[id="main"]'
  BID-1429-ES:
    path: /es/benefits/benefit-details/1429
    selector: '[id="main"]'

  BID-1449:
    path: /benefits/benefit-details/1449
    selector: '[id="main"]'
  BID-1449-ES:
    path: /es/benefits/benefit-details/1449
    selector: '[id="main"]'

  BID-1492:
    path: /benefits/benefit-details/1492
    selector: '[id="main"]'
  BID-1492-ES:
    path: /es/benefits/benefit-details/1492
    selector: '[id="main"]'

  BID-1493:
    path: /benefits/benefit-details/1493
    selector: '[id="main"]'
  BID-1493-ES:
    path: /es/benefits/benefit-details/1493
    selector: '[id="main"]'

  BID-1497:
    path: /benefits/benefit-details/1497
    selector: '[id="main"]'
  BID-1497-ES:
    path: /es/benefits/benefit-details/1497
    selector: '[id="main"]'

  BID-1498:
    path: /benefits/benefit-details/1498
    selector: '[id="main"]'
  BID-1498-ES:
    path: /es/benefits/benefit-details/1498
    selector: '[id="main"]'

  BID-1499:
    path: /benefits/benefit-details/1499
    selector: '[id="main"]'
  BID-1499-ES:
    path: /es/benefits/benefit-details/1499
    selector: '[id="main"]'

  BID-1501:
    path: /benefits/benefit-details/1501
    selector: '[id="main"]'
  BID-1501-ES:
    path: /es/benefits/benefit-details/1501
    selector: '[id="main"]'

  BID-1502:
    path: /benefits/benefit-details/1502
    selector: '[id="main"]'
  BID-1502-ES:
    path: /es/benefits/benefit-details/1502
    selector: '[id="main"]'

  BID-1503:
    path: /benefits/benefit-details/1503
    selector: '[id="main"]'
  BID-1503-ES:
    path: /es/benefits/benefit-details/1503
    selector: '[id="main"]'

  BID-1504:
    path: /benefits/benefit-details/1504
    selector: '[id="main"]'
  BID-1504-ES:
    path: /es/benefits/benefit-details/1504
    selector: '[id="main"]'

  BID-1505:
    path: /benefits/benefit-details/1505
    selector: '[id="main"]'
  BID-1505-ES:
    path: /es/benefits/benefit-details/1505
    selector: '[id="main"]'

  BID-1506:
    path: /benefits/benefit-details/1506
    selector: '[id="main"]'
  BID-1506-ES:
    path: /es/benefits/benefit-details/1506
    selector: '[id="main"]'

  BID-1507:
    path: /benefits/benefit-details/1507
    selector: '[id="main"]'
  BID-1507-ES:
    path: /es/benefits/benefit-details/1507
    selector: '[id="main"]'

  BID-1512:
    path: /benefits/benefit-details/1512
    selector: '[id="main"]'
  BID-1512-ES:
    path: /es/benefits/benefit-details/1512
    selector: '[id="main"]'

  BID-1529:
    path: /benefits/benefit-details/1529
    selector: '[id="main"]'
  BID-1529-ES:
    path: /es/benefits/benefit-details/1529
    selector: '[id="main"]'

  BID-1531:
    path: /benefits/benefit-details/1531
    selector: '[id="main"]'
  BID-1531-ES:
    path: /es/benefits/benefit-details/1531
    selector: '[id="main"]'

  BID-1534:
    path: /benefits/benefit-details/1534
    selector: '[id="main"]'
  BID-1534-ES:
    path: /es/benefits/benefit-details/1534
    selector: '[id="main"]'

  BID-1535:
    path: /benefits/benefit-details/1535
    selector: '[id="main"]'
  BID-1535-ES:
    path: /es/benefits/benefit-details/1535
    selector: '[id="main"]'

  BID-1536:
    path: /benefits/benefit-details/1536
    selector: '[id="main"]'
  BID-1536-ES:
    path: /es/benefits/benefit-details/1536
    selector: '[id="main"]'

  BID-1537:
    path: /benefits/benefit-details/1537
    selector: '[id="main"]'
  BID-1537-ES:
    path: /es/benefits/benefit-details/1537
    selector: '[id="main"]'

  BID-1538:
    path: /benefits/benefit-details/1538
    selector: '[id="main"]'
  BID-1538-ES:
    path: /es/benefits/benefit-details/1538
    selector: '[id="main"]'

  BID-1539:
    path: /benefits/benefit-details/1539
    selector: '[id="main"]'
  BID-1539-ES:
    path: /es/benefits/benefit-details/1539
    selector: '[id="main"]'

  BID-1540:
    path: /benefits/benefit-details/1540
    selector: '[id="main"]'
  BID-1540-ES:
    path: /es/benefits/benefit-details/1540
    selector: '[id="main"]'

  BID-1541:
    path: /benefits/benefit-details/1541
    selector: '[id="main"]'
  BID-1541-ES:
    path: /es/benefits/benefit-details/1541
    selector: '[id="main"]'

  BID-1542:
    path: /benefits/benefit-details/1542
    selector: '[id="main"]'
  BID-1542-ES:
    path: /es/benefits/benefit-details/1542
    selector: '[id="main"]'

  BID-1543:
    path: /benefits/benefit-details/1543
    selector: '[id="main"]'
  BID-1543-ES:
    path: /es/benefits/benefit-details/1543
    selector: '[id="main"]'

  BID-1545:
    path: /benefits/benefit-details/1545
    selector: '[id="main"]'
  BID-1545-ES:
    path: /es/benefits/benefit-details/1545
    selector: '[id="main"]'

  BID-1546:
    path: /benefits/benefit-details/1546
    selector: '[id="main"]'
  BID-1546-ES:
    path: /es/benefits/benefit-details/1546
    selector: '[id="main"]'

  BID-1548:
    path: /benefits/benefit-details/1548
    selector: '[id="main"]'
  BID-1548-ES:
    path: /es/benefits/benefit-details/1548
    selector: '[id="main"]'

  BID-1549:
    path: /benefits/benefit-details/1549
    selector: '[id="main"]'
  BID-1549-ES:
    path: /es/benefits/benefit-details/1549
    selector: '[id="main"]'

  BID-1551:
    path: /benefits/benefit-details/1551
    selector: '[id="main"]'
  BID-1551-ES:
    path: /es/benefits/benefit-details/1551
    selector: '[id="main"]'

  BID-1552:
    path: /benefits/benefit-details/1552
    selector: '[id="main"]'
  BID-1552-ES:
    path: /es/benefits/benefit-details/1552
    selector: '[id="main"]'

  BID-1553:
    path: /benefits/benefit-details/1553
    selector: '[id="main"]'
  BID-1553-ES:
    path: /es/benefits/benefit-details/1553
    selector: '[id="main"]'

  BID-1554:
    path: /benefits/benefit-details/1554
    selector: '[id="main"]'
  BID-1554-ES:
    path: /es/benefits/benefit-details/1554
    selector: '[id="main"]'

  BID-1555:
    path: /benefits/benefit-details/1555
    selector: '[id="main"]'
  BID-1555-ES:
    path: /es/benefits/benefit-details/1555
    selector: '[id="main"]'

  BID-1556:
    path: /benefits/benefit-details/1556
    selector: '[id="main"]'
  BID-1556-ES:
    path: /es/benefits/benefit-details/1556
    selector: '[id="main"]'


# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "casperjs"

phantomjs_options: --ignore-ssl-errors=yes

################################################################

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--casper.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  #- 450x650
  - 1280

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
#before_capture: 'javascript/disable_javascript--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots/capture/BG/bids/part4'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  #template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
  



