#Benefits.gov origin-www to prod

# run with "wraith capture configs/BG/BG_origin-www_to_prod.yaml"

imports: "settings_BG.yaml"

# (required) The domains to take screenshots of.
domains:
  origin-www: "https://origin-www.benefits.gov"
  prod: "https://www.benefits.gov"
