#Benefits.gov test to origin-staging

# run with "wraith capture configs/BG/BG_test_to_origin-staging.yaml"

imports: "settings_BG.yaml"

# (required) The domains to take screenshots of.
domains:
  test: "https://test.benefits.gov"
  origin-staging: "https://origin-staging.benefits.gov"
