##############################################################
##############################################################
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# run with "wraith capture configs/BG/capture_BG.yaml"
#
##############################################################
##############################################################


# (required) The domains to take screenshots of.
domains:
  origin-www: "https://origin-www.benefits.gov"
  prod: "https://www.benefits.gov"

# (required) The paths to capture. All paths should exist for both of the domains specified above.

paths:
  # header:
  #   path: /
  #   selector: ".header"
  # footer:
  #   path: /
  #   selector: ".region.region-footer"


  #Benefits.gov links
  home:
    path: /
    selector: '[id="main"]'
  EShome:
    path: /es
    selector: '[id="main"]'

  browse-by-category: 
    path: /benefits/browse-by-category
    selector: '[id="main"]'
  ES-browse-by-category: 
    path: /es/benefits/browse-by-category
    selector: '[id="main"]'
  browse-by-state:
    path: /benefits/browse-by-state
    selector: '[id="main"]'
  ES-browse-by-state: 
    path:  /es/benefits/browse-by-state
    selector: '[id="main"]'
  browse-by-agency: 
    path: /benefits/browse-by-agency
    selector: '[id="main"]'
  ES-browse-by-agency: 
    path: /es/benefits/browse-by-agency
    selector: '[id="main"]'
  other-resources: 
    path: /benefits/other-resources
    selector: '[id="main"]'
  ES-other-resources: 
    path: /es/benefits/other-resources
    selector: '[id="main"]'

  news-and-updates: 
    path: /newsroom/news-and-updates
    selector: '[id="main"]'
  ES-news-and-updates: 
    path: /es/newsroom/news-and-updates
    selector: '[id="main"]'
  compass-newsletter: 
    path: /newsroom/eNewsletter/july-2017
    selector: '[id="main"]'
  ES-compass-newsletter: 
    path: /es/newsroom/eNewsletter/july-2017
    selector: '[id="main"]'

  get-involved:
    path: /get-involved
    selector: '[id="main"]'
  ES-get-involved: 
    path: /es/involúcrese
    selector: '[id="main"]'
  become-an-advocate:
    path: /get-involved#become-an-advocate
    selector: '[id="main"]'
  ES-become-an-advocate:
    path: /es/involúcrese#conviértase-en-un-representante
    selector: '[id="main"]'
  become-an-affiliate:
    path: /get-involved#become-an-affiliate
    selector: '[id="main"]'
  ES-become-an-affiliate:
    path: /es/involúcrese#conviértase-en-un-afiliado
    selector: '[id="main"]'
  link-to-us:
    path: /get-involved#link-to-us
    selector: '[id="main"]'
  ES-link-to-us:
    path: /es/involúcrese#enlace-su-sitio-al-nuestro
    selector: '[id="main"]'

  about-us: 
    path: /about-us
    selector: '[id="main"]'
  ES-about-us: 
    path: /es/sobre-nosotros
    selector: '[id="main"]'
  our-mission:
    path: /about-us#our-mission
  ES-our-mission:
    path: /es/sobre-nosotros#nuestra-misión
  our-history:
    path: /about-us#our-history
  ES-our-history:
    path: /es/sobre-nosotros#nuestra-historia
  our-partners:
    path: /about-us#our-partners
  ES-our-partners:
    path: /es/sobre-nosotros#nuestros-socios
  become-a-partner: 
    path: /about-us#become-a-partner
  ES-become-a-partner: 
    path: /es/sobre-nosotros#conviértase-en-un-socio
  our-platform: 
    path: /about-us#our-platform
  ES-platform: 
    path: /es/sobre-nosotros#nuestra-plataforma
  recognition: 
    path: /about-us#recognition
  ES-recognition: 
    path: /es/sobre-nosotros#reconocimiento

  faq: 
    path: /help/faqs
    selector: '[id="main"]'
  ES-faq: 
    path: /es/help/faqs
    selector: '[id="main"]'
  contact-us: 
    path: /help/contact-us
    selector: '[id="main"]'
  ES-contact-us: 
    path: /es/help/contact-us
    selector: '[id="main"]'
  privacy-and-terms: 
    path: /about/privacy-and-terms-use
    selector: '[id="main"]'
  ES-privacy-and-terms: 
    path: /es/privacidad-y-términos-de-uso
    selector: '[id="main"]'

  ################################################################
  # Place BIDs to compare here
  ################################################################
  
  # BID-290:
  #   path: /benefits/benefit-details/290
  #   selector: '[id="main"]'
  # BID-290-ES:
  #   path: /es/benefits/benefit-details/290
  #   selector: '[id="main"]'

  # BID-279:
  #   path: /benefits/benefit-details/279
  #   selector: '[id="main"]'
  # BID-279-ES:
  #   path: /es/benefits/benefit-details/279
  #   selector: '[id="main"]'

  # BID-284:
  #   path: /benefits/benefit-details/284
  #   selector: '[id="main"]'
  # BID-284-ES:
  #   path: /es/benefits/benefit-details/284
  #   selector: '[id="main"]'

  # BID-4771:
  #   path: /benefits/benefit-details/4771
  #   selector: '[id="main"]'
  # BID-4771-ES:
  #   path: /es/benefits/benefit-details/4771
  #   selector: '[id="main"]'

  # BID-286:
  #   path: /benefits/benefit-details/286
  #   selector: '[id="main"]'
  # BID-286-ES:
  #   path: /es/benefits/benefit-details/286
  #   selector: '[id="main"]'

  # BID-288:
  #   path: /benefits/benefit-details/288
  #   selector: '[id="main"]'
  # BID-288-ES:
  #   path: /es/benefits/benefit-details/288
  #   selector: '[id="main"]'

  # BID-588:
  #   path: /benefits/benefit-details/588
  #   selector: '[id="main"]'
  # BID-588-ES:
  #   path: /es/benefits/benefit-details/588
  #   selector: '[id="main"]'

  # BID-4731:
  #   path: /benefits/benefit-details/4731
  #   selector: '[id="main"]'
  # BID-4731-ES:
  #   path: /es/benefits/benefit-details/4731
  #   selector: '[id="main"]'

  # BID-292:
  #   path: /benefits/benefit-details/292
  #   selector: '[id="main"]'
  # BID-292-ES:
  #   path: /es/benefits/benefit-details/292
  #   selector: '[id="main"]'

  # BID-1506:
  #   path: /benefits/benefit-details/1506
  #   selector: '[id="main"]'
  # BID-1506-ES:
  #   path: /es/benefits/benefit-details/1506
  #   selector: '[id="main"]'

  # BID-1507:
  #   path: /benefits/benefit-details/1507
  #   selector: '[id="main"]'
  # BID-1507-ES:
  #   path: /es/benefits/benefit-details/1507
  #   selector: '[id="main"]'

  # BID-5933:
  #   path: /benefits/benefit-details/5933
  #   selector: '[id="main"]'
  # BID-5933-ES:
  #   path: /es/benefits/benefit-details/5933
  #   selector: '[id="main"]'

  # BID-296:
  #   path: /benefits/benefit-details/296
  #   selector: '[id="main"]'
  # BID-296-ES:
  #   path: /es/benefits/benefit-details/296
  #   selector: '[id="main"]'

  # BID-780:
  #   path: /benefits/benefit-details/780
  #   selector: '[id="main"]'
  # BID-780-ES:
  #   path: /es/benefits/benefit-details/780
  #   selector: '[id="main"]'

  # BID-297:
  #   path: /benefits/benefit-details/297
  #   selector: '[id="main"]'
  # BID-297-ES:
  #   path: /es/benefits/benefit-details/297
  #   selector: '[id="main"]'

  # BID-300:
  #   path: /benefits/benefit-details/300
  #   selector: '[id="main"]'
  # BID-300-ES:
  #   path: /es/benefits/benefit-details/300
  #   selector: '[id="main"]'

  # BID-301:
  #   path: /benefits/benefit-details/301
  #   selector: '[id="main"]'
  # BID-301-ES:
  #   path: /es/benefits/benefit-details/301
  #   selector: '[id="main"]'

  # BID-302:
  #   path: /benefits/benefit-details/302
  #   selector: '[id="main"]'
  # BID-302-ES:
  #   path: /es/benefits/benefit-details/302
  #   selector: '[id="main"]'

  # BID-303:
  #   path: /benefits/benefit-details/303
  #   selector: '[id="main"]'
  # BID-303-ES:
  #   path: /es/benefits/benefit-details/303
  #   selector: '[id="main"]'

  # BID-304:
  #   path: /benefits/benefit-details/304
  #   selector: '[id="main"]'
  # BID-304-ES:
  #   path: /es/benefits/benefit-details/304
  #   selector: '[id="main"]'

  # BID-306:
  #   path: /benefits/benefit-details/306
  #   selector: '[id="main"]'
  # BID-306-ES:
  #   path: /es/benefits/benefit-details/306
  #   selector: '[id="main"]'

  # BID-307:
  #   path: /benefits/benefit-details/307
  #   selector: '[id="main"]'
  # BID-307-ES:
  #   path: /es/benefits/benefit-details/307
  #   selector: '[id="main"]'

  # BID-313:
  #   path: /benefits/benefit-details/313
  #   selector: '[id="main"]'
  # BID-313-ES:
  #   path: /es/benefits/benefit-details/313
  #   selector: '[id="main"]'

  # BID-1647:
  #   path: /benefits/benefit-details/1647
  #   selector: '[id="main"]'
  # BID-1647-ES:
  #   path: /es/benefits/benefit-details/1647
  #   selector: '[id="main"]'

  # BID-315:
  #   path: /benefits/benefit-details/315
  #   selector: '[id="main"]'
  # BID-315-ES:
  #   path: /es/benefits/benefit-details/315
  #   selector: '[id="main"]'

  # BID-317:
  #   path: /benefits/benefit-details/317
  #   selector: '[id="main"]'
  # BID-317-ES:
  #   path: /es/benefits/benefit-details/317
  #   selector: '[id="main"]'

  # BID-318:
  #   path: /benefits/benefit-details/318
  #   selector: '[id="main"]'
  # BID-318-ES:
  #   path: /es/benefits/benefit-details/318
  #   selector: '[id="main"]'

  # BID-319:
  #   path: /benefits/benefit-details/319
  #   selector: '[id="main"]'
  # BID-319-ES:
  #   path: /es/benefits/benefit-details/319
  #   selector: '[id="main"]'

  # BID-322:
  #   path: /benefits/benefit-details/322
  #   selector: '[id="main"]'
  # BID-322-ES:
  #   path: /es/benefits/benefit-details/322
  #   selector: '[id="main"]'

  # BID-567:
  #   path: /benefits/benefit-details/567
  #   selector: '[id="main"]'
  # BID-567-ES:
  #   path: /es/benefits/benefit-details/567
  #   selector: '[id="main"]'

  # BID-568:
  #   path: /benefits/benefit-details/568
  #   selector: '[id="main"]'
  # BID-568-ES:
  #   path: /es/benefits/benefit-details/568
  #   selector: '[id="main"]'

  # BID-569:
  #   path: /benefits/benefit-details/569
  #   selector: '[id="main"]'
  # BID-569-ES:
  #   path: /es/benefits/benefit-details/569
  #   selector: '[id="main"]'

  # BID-4743:
  #   path: /benefits/benefit-details/4743
  #   selector: '[id="main"]'
  # BID-4743-ES:
  #   path: /es/benefits/benefit-details/4743
  #   selector: '[id="main"]'

  # BID-4745:
  #   path: /benefits/benefit-details/4745
  #   selector: '[id="main"]'
  # BID-4745-ES:
  #   path: /es/benefits/benefit-details/4745
  #   selector: '[id="main"]'

  # BID-4747:
  #   path: /benefits/benefit-details/4747
  #   selector: '[id="main"]'
  # BID-4747-ES:
  #   path: /es/benefits/benefit-details/4747
  #   selector: '[id="main"]'

  # BID-4749:
  #   path: /benefits/benefit-details/4749
  #   selector: '[id="main"]'
  # BID-4749-ES:
  #   path: /es/benefits/benefit-details/4749
  #   selector: '[id="main"]'

  # BID-4753:
  #   path: /benefits/benefit-details/4753
  #   selector: '[id="main"]'
  # BID-4753-ES:
  #   path: /es/benefits/benefit-details/4753
  #   selector: '[id="main"]'

  # BID-4767:
  #   path: /benefits/benefit-details/4767
  #   selector: '[id="main"]'
  # BID-4767-ES:
  #   path: /es/benefits/benefit-details/4767
  #   selector: '[id="main"]'

  # BID-5891:
  #   path: /benefits/benefit-details/5891
  #   selector: '[id="main"]'
  # BID-5891-ES:
  #   path: /es/benefits/benefit-details/5891
  #   selector: '[id="main"]'

  # BID-5918:
  #   path: /benefits/benefit-details/5918
  #   selector: '[id="main"]'
  # BID-5918-ES:
  #   path: /es/benefits/benefit-details/5918
  #   selector: '[id="main"]'

  # BID-1617:
  #   path: /benefits/benefit-details/1617
  #   selector: '[id="main"]'
  # BID-1617-ES:
  #   path: /es/benefits/benefit-details/1617
  #   selector: '[id="main"]'




# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "casperjs"

phantomjs_options: --ignore-ssl-errors=yes --ssl-protocol=tlsv1

################################################################

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--casper.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  #- 450x650
  - 1280

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
#before_capture: 'javascript/disable_javascript--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots/capture/BG'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
  



