##############################################################
##############################################################
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# run with "wraith capture configs/BG/capture_BG.yaml"
#
##############################################################
##############################################################


# (required) The domains to take screenshots of.
domains:
  edit: "https://edit.benefits.gov"
  prod: "https://www.benefits.gov"

# (required) The paths to capture. All paths should exist for both of the domains specified above.

paths:
  # header:
  #   path: /
  #   selector: ".header"
  # footer:
  #   path: /
  #   selector: ".region.region-footer"


  #Benefits.gov links
  home:
    path: /
    selector: '[id="main"]'
  EShome:
    path: /es
    selector: '[id="main"]'

  browse-by-category: 
    path: /benefits/browse-by-category
    selector: '[id="main"]'
  ES-browse-by-category: 
    path: /es/benefits/browse-by-category
    selector: '[id="main"]'
  browse-by-state:
    path: /benefits/browse-by-state
    selector: '[id="main"]'
  ES-browse-by-state: 
    path:  /es/benefits/browse-by-state
    selector: '[id="main"]'
  browse-by-agency: 
    path: /benefits/browse-by-agency
    selector: '[id="main"]'
  ES-browse-by-agency: 
    path: /es/benefits/browse-by-agency
    selector: '[id="main"]'
  other-resources: 
    path: /benefits/other-resources
    selector: '[id="main"]'
  ES-other-resources: 
    path: /es/benefits/other-resources
    selector: '[id="main"]'

  news-and-updates: 
    path: /newsroom/news-and-updates
    selector: '[id="main"]'
  ES-news-and-updates: 
    path: /es/newsroom/news-and-updates
    selector: '[id="main"]'
  compass-newsletter: 
    path: /newsroom/eNewsletter/april-2017
    selector: '[id="main"]'
  ES-compass-newsletter: 
    path: /es/newsroom/eNewsletter/april-2017
    selector: '[id="main"]'

  get-involved:
    path: /get-involved
    selector: '[id="main"]'
  ES-get-involved: 
    path: /es/involúcrese
    selector: '[id="main"]'
  become-an-advocate:
    path: /get-involved#become-an-advocate
    selector: '[id="main"]'
  ES-become-an-advocate:
    path: /es/involúcrese#conviértase-en-un-representante
    selector: '[id="main"]'
  become-an-affiliate:
    path: /get-involved#become-an-affiliate
    selector: '[id="main"]'
  ES-become-an-affiliate:
    path: /es/involúcrese#conviértase-en-un-afiliado
    selector: '[id="main"]'
  link-to-us:
    path: /get-involved#link-to-us
    selector: '[id="main"]'
  ES-link-to-us:
    path: /es/involúcrese#enlace-su-sitio-al-nuestro
    selector: '[id="main"]'

  about-us: 
    path: /about-us
    selector: '[id="main"]'
  ES-about-us: 
    path: /es/sobre-nosotros
    selector: '[id="main"]'
  our-mission:
    path: /about-us#our-mission
  ES-our-mission:
    path: /es/sobre-nosotros#nuestra-misión
  our-history:
    path: /about-us#our-history
  ES-our-history:
    path: /es/sobre-nosotros#nuestra-historia
  our-partners:
    path: /about-us#our-partners
  ES-our-partners:
    path: /es/sobre-nosotros#nuestros-socios
  become-a-partner: 
    path: /about-us#become-a-partner
  ES-become-a-partner: 
    path: /es/sobre-nosotros#conviértase-en-un-socio
  our-platform: 
    path: /about-us#our-platform
  ES-platform: 
    path: /es/sobre-nosotros#nuestra-plataforma
  recognition: 
    path: /about-us#recognition
  ES-recognition: 
    path: /es/sobre-nosotros#reconocimiento

  faq: 
    path: /help/faqs
    selector: '[id="main"]'
  ES-faq: 
    path: /es/help/faqs
    selector: '[id="main"]'
  contact-us: 
    path: /help/contact-us
    selector: '[id="main"]'
  ES-contact-us: 
    path: /es/help/contact-us
    selector: '[id="main"]'
  privacy-and-terms: 
    path: /about/privacy-and-terms-use
    selector: '[id="main"]'
  ES-privacy-and-terms: 
    path: /es/privacidad-y-términos-de-uso
    selector: '[id="main"]'

  ################################################################
  # Place BIDs to compare here
  ################################################################
  
  BID-785:
    path: /benefits/benefit-details/785
    selector: '[id="main"]'
  BID-785-ES:
    path: /es/benefits/benefit-details/785
    selector: '[id="main"]'

  BID-474:
    path: /benefits/benefit-details/474
    selector: '[id="main"]'
  BID-474-ES:
    path: /es/benefits/benefit-details/474
    selector: '[id="main"]'

  BID-480:
    path: /benefits/benefit-details/480
    selector: '[id="main"]'
  BID-480-ES:
    path: /es/benefits/benefit-details/480
    selector: '[id="main"]'

  BID-700:
    path: /benefits/benefit-details/700
    selector: '[id="main"]'
  BID-700-ES:
    path: /es/benefits/benefit-details/700
    selector: '[id="main"]'

  BID-386:
    path: /benefits/benefit-details/386
    selector: '[id="main"]'
  BID-386-ES:
    path: /es/benefits/benefit-details/386
    selector: '[id="main"]'

  BID-1587:
    path: /benefits/benefit-details/1587
    selector: '[id="main"]'
  BID-1587-ES:
    path: /es/benefits/benefit-details/1587
    selector: '[id="main"]'

  BID-4759:
    path: /benefits/benefit-details/4759
    selector: '[id="main"]'
  BID-4759-ES:
    path: /es/benefits/benefit-details/4759
    selector: '[id="main"]'

  BID-281:
    path: /benefits/benefit-details/281
    selector: '[id="main"]'
  BID-281-ES:
    path: /es/benefits/benefit-details/281
    selector: '[id="main"]'

  BID-1503:
    path: /benefits/benefit-details/1503
    selector: '[id="main"]'
  BID-1503-ES:
    path: /es/benefits/benefit-details/1503
    selector: '[id="main"]'

  BID-1499:
    path: /benefits/benefit-details/1499
    selector: '[id="main"]'
  BID-1499-ES:
    path: /es/benefits/benefit-details/1499
    selector: '[id="main"]'

  BID-1050:
    path: /benefits/benefit-details/1050
    selector: '[id="main"]'
  BID-1050-ES:
    path: /es/benefits/benefit-details/1050
    selector: '[id="main"]'

  BID-1580:
    path: /benefits/benefit-details/1580
    selector: '[id="main"]'
  BID-1580-ES:
    path: /es/benefits/benefit-details/1580
    selector: '[id="main"]'

  BID-1236:
    path: /benefits/benefit-details/1236
    selector: '[id="main"]'
  BID-1236-ES:
    path: /es/benefits/benefit-details/1236
    selector: '[id="main"]'

  BID-1244:
    path: /benefits/benefit-details/1244
    selector: '[id="main"]'
  BID-1244-ES:
    path: /es/benefits/benefit-details/1244
    selector: '[id="main"]'

  BID-1312:
    path: /benefits/benefit-details/1312
    selector: '[id="main"]'
  BID-1312-ES:
    path: /es/benefits/benefit-details/1312
    selector: '[id="main"]'

  BID-1913:
    path: /benefits/benefit-details/1913
    selector: '[id="main"]'
  BID-1913-ES:
    path: /es/benefits/benefit-details/1913
    selector: '[id="main"]'

  BID-1914:
    path: /benefits/benefit-details/1914
    selector: '[id="main"]'
  BID-1914-ES:
    path: /es/benefits/benefit-details/1914
    selector: '[id="main"]'

  BID-1915:
    path: /benefits/benefit-details/1915
    selector: '[id="main"]'
  BID-1915-ES:
    path: /es/benefits/benefit-details/1915
    selector: '[id="main"]'

  BID-1916:
    path: /benefits/benefit-details/1916
    selector: '[id="main"]'
  BID-1916-ES:
    path: /es/benefits/benefit-details/1916
    selector: '[id="main"]'

  BID-1918:
    path: /benefits/benefit-details/1918
    selector: '[id="main"]'
  BID-1918-ES:
    path: /es/benefits/benefit-details/1918
    selector: '[id="main"]'

  BID-1919:
    path: /benefits/benefit-details/1919
    selector: '[id="main"]'
  BID-1919-ES:
    path: /es/benefits/benefit-details/1919
    selector: '[id="main"]'

  BID-1920:
    path: /benefits/benefit-details/1920
    selector: '[id="main"]'
  BID-1920-ES:
    path: /es/benefits/benefit-details/1920
    selector: '[id="main"]'

  BID-1921:
    path: /benefits/benefit-details/1921
    selector: '[id="main"]'
  BID-1921-ES:
    path: /es/benefits/benefit-details/1921
    selector: '[id="main"]'

  BID-1923:
    path: /benefits/benefit-details/1923
    selector: '[id="main"]'
  BID-1923-ES:
    path: /es/benefits/benefit-details/1923
    selector: '[id="main"]'

  BID-1924:
    path: /benefits/benefit-details/1924
    selector: '[id="main"]'
  BID-1924-ES:
    path: /es/benefits/benefit-details/1924
    selector: '[id="main"]'

  BID-1926:
    path: /benefits/benefit-details/1926
    selector: '[id="main"]'
  BID-1926-ES:
    path: /es/benefits/benefit-details/1926
    selector: '[id="main"]'

  BID-1927:
    path: /benefits/benefit-details/1927
    selector: '[id="main"]'
  BID-1927-ES:
    path: /es/benefits/benefit-details/1927
    selector: '[id="main"]'

  BID-1928:
    path: /benefits/benefit-details/1928
    selector: '[id="main"]'
  BID-1928-ES:
    path: /es/benefits/benefit-details/1928
    selector: '[id="main"]'

  BID-1929:
    path: /benefits/benefit-details/1929
    selector: '[id="main"]'
  BID-1929-ES:
    path: /es/benefits/benefit-details/1929
    selector: '[id="main"]'

  BID-1930:
    path: /benefits/benefit-details/1930
    selector: '[id="main"]'
  BID-1930-ES:
    path: /es/benefits/benefit-details/1930
    selector: '[id="main"]'

  BID-1932:
    path: /benefits/benefit-details/1932
    selector: '[id="main"]'
  BID-1932-ES:
    path: /es/benefits/benefit-details/1932
    selector: '[id="main"]'

  BID-1934:
    path: /benefits/benefit-details/1934
    selector: '[id="main"]'
  BID-1934-ES:
    path: /es/benefits/benefit-details/1934
    selector: '[id="main"]'

  BID-1935:
    path: /benefits/benefit-details/1935
    selector: '[id="main"]'
  BID-1935-ES:
    path: /es/benefits/benefit-details/1935
    selector: '[id="main"]'

  BID-1937:
    path: /benefits/benefit-details/1937
    selector: '[id="main"]'
  BID-1937-ES:
    path: /es/benefits/benefit-details/1937
    selector: '[id="main"]'

  BID-4341:
    path: /benefits/benefit-details/4341
    selector: '[id="main"]'
  BID-4341-ES:
    path: /es/benefits/benefit-details/4341
    selector: '[id="main"]'

  BID-1958:
    path: /benefits/benefit-details/1958
    selector: '[id="main"]'
  BID-1958-ES:
    path: /es/benefits/benefit-details/1958
    selector: '[id="main"]'

  BID-2086:
    path: /benefits/benefit-details/2086
    selector: '[id="main"]'
  BID-2086-ES:
    path: /es/benefits/benefit-details/2086
    selector: '[id="main"]'

  BID-1229:
    path: /benefits/benefit-details/1229
    selector: '[id="main"]'
  BID-1229-ES:
    path: /es/benefits/benefit-details/1229
    selector: '[id="main"]'

  BID-1228:
    path: /benefits/benefit-details/1228
    selector: '[id="main"]'
  BID-1228-ES:
    path: /es/benefits/benefit-details/1228
    selector: '[id="main"]'

  BID-1602:
    path: /benefits/benefit-details/1602
    selector: '[id="main"]'
  BID-1602-ES:
    path: /es/benefits/benefit-details/1602
    selector: '[id="main"]'

  BID-1251:
    path: /benefits/benefit-details/1251
    selector: '[id="main"]'
  BID-1251-ES:
    path: /es/benefits/benefit-details/1251
    selector: '[id="main"]'

  BID-4573:
    path: /benefits/benefit-details/4573
    selector: '[id="main"]'
  BID-4573-ES:
    path: /es/benefits/benefit-details/4573
    selector: '[id="main"]'

  BID-798:
    path: /benefits/benefit-details/798
    selector: '[id="main"]'
  BID-798-ES:
    path: /es/benefits/benefit-details/798
    selector: '[id="main"]'

  BID-801:
    path: /benefits/benefit-details/801
    selector: '[id="main"]'
  BID-801-ES:
    path: /es/benefits/benefit-details/801
    selector: '[id="main"]'

  BID-636:
    path: /benefits/benefit-details/636
    selector: '[id="main"]'
  BID-636-ES:
    path: /es/benefits/benefit-details/636
    selector: '[id="main"]'


  



