#Govloans.gov spanish compare staging to prod

# run with "wraith capture configs/GL/GL-ES-staging-to-prod.yaml"

imports: "settings-GL-ES.yaml"

# (required) The domains to take screenshots of.
domains:
  staging: "https://es.staging.govloans.gov"
  prod: "https://es.govloans.gov"
