#Govloans.gov compare origin-www to prod

# run with "wraith capture configs/GL/GL_EN_origin-www_to_prod.yaml"

imports: "settings_GL_EN.yaml"

# (required) The domains to take screenshots of.
domains:
  origin-www: "https://origin-www.govloans.gov"
  prod: "https://www.govloans.gov"
