#Govloans.gov compare edit to prod

# run with "wraith capture configs/GL/GL_ES_edit_to_prod.yaml"

imports: "settings_GL_ES.yaml"

# (required) The domains to take screenshots of.
domains:
  edit: "https://es.edit.govloans.gov"
  prod: "https://es.govloans.gov"
