#Govloans.gov compare test to origin-staging

# run with "wraith capture configs/GL/GL_EN_test_to_origin-staging.yaml"

imports: "settings_GL_EN.yaml"

# (required) The domains to take screenshots of.
domains:
  test: "https://test.govloans.gov"
  origin-staging: "https://origin-staging.govloans.gov"
