#Govloans.gov compare edit to prod

# run with "wraith capture configs/GL/GL_EN_edit_to_prod.yaml"

imports: "settings_GL_EN.yaml"

# (required) The domains to take screenshots of.
domains:
  edit: "https://edit.govloans.gov"
  prod: "https://www.govloans.gov"
