#Govloans.gov compare origin-staging to origin-www

# run with "wraith capture configs/GL/GL_EN_origin-staging_to_origin-www.yaml"

imports: "settings_GL_EN.yaml"

# (required) The domains to take screenshots of.
domains:
  origin-staging: "https://origin-staging.govloans.gov"
  origin-www: "https://origin-www.govloans.gov"
