#Govloans.gov compare origin-www to prod

# run with "wraith capture configs/GL/GL_ES_origin-www_to_prod.yaml"

imports: "settings_GL_ES.yaml"

# (required) The domains to take screenshots of.
domains:
  origin-www: "https://es.origin-www.govloans.gov"
  prod: "https://es.govloans.gov"
