#ssabest.benefits.gov compare staging to prod

# run with "wraith capture configs/SSA/SSA-staging-to-prod.yaml"

imports: "settings-SSA.yaml"

# (required) The domains to take screenshots of.
domains:
  staging: "https://staging.ssabest.benefits.gov"
  prod: "https://ssabest.benefits.gov"
