#ssabest.benefits.gov compare origin-staging to origin-www

# run with "wraith capture configs/SSA/SSA_origin-staging_to_origin-www.yaml"

imports: "settings_SSA.yaml"

# (required) The domains to take screenshots of.
domains:
  origin-staging: "https://origin-staging.ssabest.benefits.gov"
  origin-www: "https://origin-www.ssabest.benefits.gov"
