##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# run with 'wraith capture configs/SSA/fullSitemap/categories-SSA.yaml'
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "casperjs"

phantomjs_options: --ignore-ssl-errors=yes

# (required) The domains to take screenshots of.
domains:
  prod: "https://ssabest.benefits.gov"
  staging: "https://staging.ssabest.benefits.gov"

# (required) The paths to capture. All paths should exist for both of the domains specified above.

paths:

  #SSABest Links
  #8 categories

  browse-by-category:
    path: /benefits/browse-by-category
    selector: ".js"
  browse-by-category-ES:
    path: /es/benefits/browse-by-category
    selector: ".js"

  Category-53:
    path: /benefits/browse-by-category/category/53
    selector: ".js"
  Category-53-ES:
    path: /es/benefits/browse-by-category/category/53
    selector: ".js" 

  Category-54:
    path: /benefits/browse-by-category/category/54
    selector: ".js"
  Category-54-ES:
    path: /es/benefits/browse-by-category/category/54
    selector: ".js"

  Category-55:
    path: /benefits/browse-by-category/category/55
    selector: ".js"
  Category-55-ES:
    path: /es/benefits/browse-by-category/category/55
    selector: ".js"
    
  Category-56:
    path: /benefits/browse-by-category/category/56
    selector: ".js"
  Category-56-ES:
    path: /es/benefits/browse-by-category/category/56
    selector: ".js"
    
  Category-57:
    path: /benefits/browse-by-category/category/57
    selector: ".js"
  Category-57-ES:
    path: /es/benefits/browse-by-category/category/57
    selector: ".js"
    
  Category-58:
    path: /benefits/browse-by-category/category/58
    selector: ".js"
  Category-58-ES:
    path: /es/benefits/browse-by-category/category/58
    selector: ".js"
    
  Category-59:
    path: /benefits/browse-by-category/category/59
    selector: ".js"
  Category-59-ES:
    path: /es/benefits/browse-by-category/category/59
    selector: ".js"      

  Category-60:
    path: /benefits/browse-by-category/category/60
    selector: ".js"
  Category-60-ES:
    path: /es/benefits/browse-by-category/category/60
    selector: ".js" 

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--casper.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  #- 450x650
  - 1280

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
#before_capture: 'javascript/disable_javascript--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots/capture/SSA/fullSitemap/categories'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  #template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
